//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CulturalCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubWork
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string DateStart { get; set; }
        public long ClubTipeId { get; set; }
        public long RoomId { get; set; }
        public long ScheduleTypeId { get; set; }
        public Nullable<long> FirstLessonId { get; set; }
        public Nullable<long> SecondlessonId { get; set; }
        public Nullable<long> ThirdLessonId { get; set; }
        public string TimeStart { get; set; }
        public string TimeEnd { get; set; }
        public long TeacherId { get; set; }
    
        public virtual CheduleType CheduleType { get; set; }
        public virtual ClubType ClubType { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual WeekDay WeekDay { get; set; }
        public virtual WeekDay WeekDay1 { get; set; }
        public virtual WeekDay WeekDay2 { get; set; }
        public virtual Room Room { get; set; }
    }
}
