//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CulturalCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public long Id { get; set; }
        public long EventTypeId { get; set; }
        public string Date { get; set; }
        public string Description { get; set; }
    
        public virtual EventType EventType { get; set; }
    }
}
