//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CulturalCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentRoom
    {
        public long Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public long EventId { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public long RoomId { get; set; }
        public string Comment { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Room Room { get; set; }
    }
}
